server:
  address: 0.0.0.0
  port: 8080
  jpa:
    generate-ddl: true

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
  application:
    name: call-center

activemq:
  brokerUrl: ${ACTIVEMQ_BROKER_URL:vm://embedded?broker.persistent=false,useShutdownHook=false}

queue:
  name: ${QUEUE_NAME:mainQueue}
worker:
  name: ${HOSTNAME:worker1}
  enabled: ${WORKER_ENABLED:true}
store:
  enabled: ${STORE_ENABLED:true}